Repository Modu-Algorithm/Algorithm-Repository, pull requests merged in 2023-05, with the labels that each got.

#6 [Leetcode 199] Wonseok Solution
  Leetcode/199/Wonseok/solution.cpp
Labels: Medium, Tree

#3 [BOJ 12864] DVOfficer
  boj/12864/DivisonOfficer/README.md
  boj/12864/DivisonOfficer/main.cpp
Labels: DP, Platinum, Stack

#4 [BOJ 10999] Solution by DivisonOfficer
  boj/10999/DivisonOfficer/README.md
  boj/10999/DivisonOfficer/main.cpp
Labels: Platinum, Segment Tree

#8 [Leetcode 105] Wonseok Solution
  Leetcode/105/Wonseok/README.md
  Leetcode/105/Wonseok/solution.cpp
Labels: Medium, Tree, Recursion
